name: Publish Crate

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Extract crate version
        id: metadata
        run: |
          version=$(cargo metadata --no-deps --format-version 1 | python3 -c "import json,sys; print(json.load(sys.stdin)['packages'][0]['version'])")
          echo "crate_version=$version" >> "$GITHUB_OUTPUT"
      - name: Cargo publish
        run: cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.metadata.outputs.crate_version }}
          release_name: greentic-interfaces v${{ steps.metadata.outputs.crate_version }}
          body: |
            Automated release for greentic-interfaces v${{ steps.metadata.outputs.crate_version }}.
          target_commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
